## YAML Template.
---
production:
  project.name: U5
  facility.name: Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004

development:
  project.name: U5
  facility.name: Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004

test: &TEST
  project.name: U5
  facility.name: Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004