
production:
  label.encounter.map: MEDICAL HISTORY|MEDICAL HISTORY,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,SURGICAL HISTORY|SURGICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,UNDER 5 VISIT|UNDER 5 VISIT,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,IMMUNIZATION RECORD|IMMUNIZATION RECORD
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: UNDER 5 VISIT|TODAY,ASSESSMENT|TODAY,INITIAL NEW BORN RECORD|EXISTS,REASON FOR SPECIAL CARE|RECENT,IMMUNIZATION RECORD|RECENT,MEDICAL HISTORY|RECENT,FAMILY MEDICAL HISTORY|RECENT,SUPPLEMENTATION|TODAY,SURGICAL HISTORY|RECENT
  concept: UNDER 5 VISIT|Weight,ASSESSMENT|Cyanosis,REASON FOR SPECIAL CARE|Weight less than 2500g,IMMUNIZATION RECORD|Mother HIV Status,MEDICAL HISTORY|Child ever had asthma?,FAMILY MEDICAL HISTORY|Has family a history of allergies?,SUPPLEMENTATION|Visit date,SURGICAL HISTORY|Ever had any surgical procedure?
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

development:
  label.encounter.map: MEDICAL HISTORY|MEDICAL HISTORY,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,SURGICAL HISTORY|SURGICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,UNDER 5 VISIT|UNDER 5 VISIT,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,IMMUNIZATION RECORD|IMMUNIZATION RECORD
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: UNDER 5 VISIT|TODAY,ASSESSMENT|TODAY,INITIAL NEW BORN RECORD|EXISTS,REASON FOR SPECIAL CARE|RECENT,IMMUNIZATION RECORD|RECENT,MEDICAL HISTORY|RECENT,FAMILY MEDICAL HISTORY|RECENT,SUPPLEMENTATION|TODAY,SURGICAL HISTORY|RECENT
  concept: UNDER 5 VISIT|Weight,ASSESSMENT|Cyanosis,REASON FOR SPECIAL CARE|Weight less than 2500g,IMMUNIZATION RECORD|Mother HIV Status,MEDICAL HISTORY|Child ever had asthma?,FAMILY MEDICAL HISTORY|Has family a history of allergies?,SUPPLEMENTATION|Visit date,SURGICAL HISTORY|Ever had any surgical procedure?
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

test: &TEST
  label.encounter.map: MEDICAL HISTORY|MEDICAL HISTORY,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,SURGICAL HISTORY|SURGICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,UNDER 5 VISIT|UNDER 5 VISIT,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,IMMUNIZATION RECORD|IMMUNIZATION RECORD
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: UNDER 5 VISIT|TODAY,ASSESSMENT|TODAY,INITIAL NEW BORN RECORD|EXISTS,REASON FOR SPECIAL CARE|RECENT,IMMUNIZATION RECORD|RECENT,MEDICAL HISTORY|RECENT,FAMILY MEDICAL HISTORY|RECENT,SUPPLEMENTATION|TODAY,SURGICAL HISTORY|RECENT
  concept: UNDER 5 VISIT|Weight,ASSESSMENT|Cyanosis,REASON FOR SPECIAL CARE|Weight less than 2500g,IMMUNIZATION RECORD|Mother HIV Status,MEDICAL HISTORY|Child ever had asthma?,FAMILY MEDICAL HISTORY|Has family a history of allergies?,SUPPLEMENTATION|Visit date,SURGICAL HISTORY|Ever had any surgical procedure?
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

assessment: u5_protocol_patients

family_medical_history: u5_protocol_patients

immunization_record: u5_protocol_patients

initial_new_born_record: u5_protocol_patients

medical_history: u5_protocol_patients

reason_for_special_care: u5_protocol_patients

supplementation: u5_protocol_patients

surgical_history: u5_protocol_patients

under_5_visit: u5_protocol_patients
