
production:
  label.encounter.map: SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,MEDICAL HISTORY|MEDICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,IMMUNIZATION RECORD|IMMUNIZATION RECORD,UNDER 5 VISIT|UNDER 5 VISIT,SURGICAL HISTORY|SURGICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: SURGICAL HISTORY|RECENT,UNDER 5 VISIT|TODAY,FAMILY MEDICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,IMMUNIZATION RECORD|RECENT,REASON FOR SPECIAL CARE|RECENT,ASSESSMENT|TODAY,MEDICAL HISTORY|RECENT,SUPPLEMENTATION|TODAY
  concept: SURGICAL HISTORY|Ever had any surgical procedure?,UNDER 5 VISIT|Weight,FAMILY MEDICAL HISTORY|Has family a history of allergies?,IMMUNIZATION RECORD|Mother HIV Status,REASON FOR SPECIAL CARE|Weight less than 2500g,ASSESSMENT|Cyanosis,MEDICAL HISTORY|Child ever had asthma?,SUPPLEMENTATION|Visit date
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

development:
  label.encounter.map: SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,MEDICAL HISTORY|MEDICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,IMMUNIZATION RECORD|IMMUNIZATION RECORD,UNDER 5 VISIT|UNDER 5 VISIT,SURGICAL HISTORY|SURGICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: SURGICAL HISTORY|RECENT,UNDER 5 VISIT|TODAY,FAMILY MEDICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,IMMUNIZATION RECORD|RECENT,REASON FOR SPECIAL CARE|RECENT,ASSESSMENT|TODAY,MEDICAL HISTORY|RECENT,SUPPLEMENTATION|TODAY
  concept: SURGICAL HISTORY|Ever had any surgical procedure?,UNDER 5 VISIT|Weight,FAMILY MEDICAL HISTORY|Has family a history of allergies?,IMMUNIZATION RECORD|Mother HIV Status,REASON FOR SPECIAL CARE|Weight less than 2500g,ASSESSMENT|Cyanosis,MEDICAL HISTORY|Child ever had asthma?,SUPPLEMENTATION|Visit date
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

test: &TEST
  label.encounter.map: SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,MEDICAL HISTORY|MEDICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,IMMUNIZATION RECORD|IMMUNIZATION RECORD,UNDER 5 VISIT|UNDER 5 VISIT,SURGICAL HISTORY|SURGICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: SURGICAL HISTORY|RECENT,UNDER 5 VISIT|TODAY,FAMILY MEDICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,IMMUNIZATION RECORD|RECENT,REASON FOR SPECIAL CARE|RECENT,ASSESSMENT|TODAY,MEDICAL HISTORY|RECENT,SUPPLEMENTATION|TODAY
  concept: SURGICAL HISTORY|Ever had any surgical procedure?,UNDER 5 VISIT|Weight,FAMILY MEDICAL HISTORY|Has family a history of allergies?,IMMUNIZATION RECORD|Mother HIV Status,REASON FOR SPECIAL CARE|Weight less than 2500g,ASSESSMENT|Cyanosis,MEDICAL HISTORY|Child ever had asthma?,SUPPLEMENTATION|Visit date
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

assessment: u5_protocol_patients

family_medical_history: u5_protocol_patients

immunization_record: u5_protocol_patients

initial_new_born_record: u5_protocol_patients

medical_history: u5_protocol_patients

reason_for_special_care: u5_protocol_patients

supplementation: u5_protocol_patients

surgical_history: u5_protocol_patients

under_5_visit: u5_protocol_patients
