
production:
  label.encounter.map: INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,IMMUNIZATION RECORD|IMMUNIZATION RECORD,SURGICAL HISTORY|SURGICAL HISTORY,MEDICAL HISTORY|MEDICAL HISTORY,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,UNDER 5 VISIT|UNDER 5 VISIT,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: INITIAL NEW BORN RECORD|EXISTS,UNDER 5 VISIT|TODAY,MEDICAL HISTORY|RECENT,SURGICAL HISTORY|RECENT,ASSESSMENT|TODAY,SUPPLEMENTATION|TODAY,FAMILY MEDICAL HISTORY|RECENT,IMMUNIZATION RECORD|RECENT,REASON FOR SPECIAL CARE|RECENT
  concept: UNDER 5 VISIT|Weight,MEDICAL HISTORY|Child ever had asthma?,SURGICAL HISTORY|Ever had any surgical procedure?,ASSESSMENT|Cyanosis,SUPPLEMENTATION|Visit date,FAMILY MEDICAL HISTORY|Has family a history of allergies?,IMMUNIZATION RECORD|Mother HIV Status,REASON FOR SPECIAL CARE|Weight less than 2500g
  label: ASSESSMENT|Assessment,SUPPLEMENTATION|Supplementation

development:
  label.encounter.map: INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,IMMUNIZATION RECORD|IMMUNIZATION RECORD,SURGICAL HISTORY|SURGICAL HISTORY,MEDICAL HISTORY|MEDICAL HISTORY,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,UNDER 5 VISIT|UNDER 5 VISIT,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: INITIAL NEW BORN RECORD|EXISTS,UNDER 5 VISIT|TODAY,MEDICAL HISTORY|RECENT,SURGICAL HISTORY|RECENT,ASSESSMENT|TODAY,SUPPLEMENTATION|TODAY,FAMILY MEDICAL HISTORY|RECENT,IMMUNIZATION RECORD|RECENT,REASON FOR SPECIAL CARE|RECENT
  concept: UNDER 5 VISIT|Weight,MEDICAL HISTORY|Child ever had asthma?,SURGICAL HISTORY|Ever had any surgical procedure?,ASSESSMENT|Cyanosis,SUPPLEMENTATION|Visit date,FAMILY MEDICAL HISTORY|Has family a history of allergies?,IMMUNIZATION RECORD|Mother HIV Status,REASON FOR SPECIAL CARE|Weight less than 2500g
  label: ASSESSMENT|Assessment,SUPPLEMENTATION|Supplementation

test: &TEST
  label.encounter.map: INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,IMMUNIZATION RECORD|IMMUNIZATION RECORD,SURGICAL HISTORY|SURGICAL HISTORY,MEDICAL HISTORY|MEDICAL HISTORY,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,UNDER 5 VISIT|UNDER 5 VISIT,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: INITIAL NEW BORN RECORD|EXISTS,UNDER 5 VISIT|TODAY,MEDICAL HISTORY|RECENT,SURGICAL HISTORY|RECENT,ASSESSMENT|TODAY,SUPPLEMENTATION|TODAY,FAMILY MEDICAL HISTORY|RECENT,IMMUNIZATION RECORD|RECENT,REASON FOR SPECIAL CARE|RECENT
  concept: UNDER 5 VISIT|Weight,MEDICAL HISTORY|Child ever had asthma?,SURGICAL HISTORY|Ever had any surgical procedure?,ASSESSMENT|Cyanosis,SUPPLEMENTATION|Visit date,FAMILY MEDICAL HISTORY|Has family a history of allergies?,IMMUNIZATION RECORD|Mother HIV Status,REASON FOR SPECIAL CARE|Weight less than 2500g
  label: ASSESSMENT|Assessment,SUPPLEMENTATION|Supplementation

assessment: u5_protocol_patients

family_medical_history: u5_protocol_patients

immunization_record: u5_protocol_patients

initial_new_born_record: u5_protocol_patients

medical_history: u5_protocol_patients

reason_for_special_care: u5_protocol_patients

supplementation: u5_protocol_patients

surgical_history: u5_protocol_patients

under_5_visit: u5_protocol_patients
