
production:
  label.encounter.map: REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,SURGICAL HISTORY|SURGICAL HISTORY,IMMUNIZATION RECORD|IMMUNIZATION RECORD,UNDER 5 VISIT|UNDER 5 VISIT,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,MEDICAL HISTORY|MEDICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: SUPPLEMENTATION|TODAY,MEDICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,IMMUNIZATION RECORD|RECENT,SURGICAL HISTORY|RECENT,REASON FOR SPECIAL CARE|RECENT,UNDER 5 VISIT|TODAY,FAMILY MEDICAL HISTORY|RECENT,ASSESSMENT|TODAY
  concept: SUPPLEMENTATION|Have long-lasting insecticidal nets for malaria been given?,MEDICAL HISTORY|Child ever had asthma?,IMMUNIZATION RECORD|Mother HIV Status,SURGICAL HISTORY|Ever had any surgical procedure?,REASON FOR SPECIAL CARE|Weight less than 2500g,UNDER 5 VISIT|Weight,FAMILY MEDICAL HISTORY|Has family a history of allergies?,ASSESSMENT|Cyanosis
  label: ASSESSMENT|Assessment,SUPPLEMENTATION|Supplementation

development:
  label.encounter.map: REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,SURGICAL HISTORY|SURGICAL HISTORY,IMMUNIZATION RECORD|IMMUNIZATION RECORD,UNDER 5 VISIT|UNDER 5 VISIT,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,MEDICAL HISTORY|MEDICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: SUPPLEMENTATION|TODAY,MEDICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,IMMUNIZATION RECORD|RECENT,SURGICAL HISTORY|RECENT,REASON FOR SPECIAL CARE|RECENT,UNDER 5 VISIT|TODAY,FAMILY MEDICAL HISTORY|RECENT,ASSESSMENT|TODAY
  concept: SUPPLEMENTATION|Have long-lasting insecticidal nets for malaria been given?,MEDICAL HISTORY|Child ever had asthma?,IMMUNIZATION RECORD|Mother HIV Status,SURGICAL HISTORY|Ever had any surgical procedure?,REASON FOR SPECIAL CARE|Weight less than 2500g,UNDER 5 VISIT|Weight,FAMILY MEDICAL HISTORY|Has family a history of allergies?,ASSESSMENT|Cyanosis
  label: ASSESSMENT|Assessment,SUPPLEMENTATION|Supplementation

test: &TEST
  label.encounter.map: REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY,SURGICAL HISTORY|SURGICAL HISTORY,IMMUNIZATION RECORD|IMMUNIZATION RECORD,UNDER 5 VISIT|UNDER 5 VISIT,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,MEDICAL HISTORY|MEDICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: SUPPLEMENTATION|TODAY,MEDICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,IMMUNIZATION RECORD|RECENT,SURGICAL HISTORY|RECENT,REASON FOR SPECIAL CARE|RECENT,UNDER 5 VISIT|TODAY,FAMILY MEDICAL HISTORY|RECENT,ASSESSMENT|TODAY
  concept: SUPPLEMENTATION|Have long-lasting insecticidal nets for malaria been given?,MEDICAL HISTORY|Child ever had asthma?,IMMUNIZATION RECORD|Mother HIV Status,SURGICAL HISTORY|Ever had any surgical procedure?,REASON FOR SPECIAL CARE|Weight less than 2500g,UNDER 5 VISIT|Weight,FAMILY MEDICAL HISTORY|Has family a history of allergies?,ASSESSMENT|Cyanosis
  label: ASSESSMENT|Assessment,SUPPLEMENTATION|Supplementation

assessment: u5_protocol_patients

family_medical_history: u5_protocol_patients

immunization_record: u5_protocol_patients

initial_new_born_record: u5_protocol_patients

medical_history: u5_protocol_patients

reason_for_special_care: u5_protocol_patients

supplementation: u5_protocol_patients

surgical_history: u5_protocol_patients

under_5_visit: u5_protocol_patients
