
production:
  label.encounter.map: UNDER 5 VISIT|UNDER 5 VISIT,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,IMMUNIZATION RECORD|IMMUNIZATION RECORD,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,MEDICAL HISTORY|MEDICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,SURGICAL HISTORY|SURGICAL HISTORY,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: REASON FOR SPECIAL CARE|RECENT,UNDER 5 VISIT|TODAY,SURGICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,SUPPLEMENTATION|TODAY,MEDICAL HISTORY|RECENT,IMMUNIZATION RECORD|RECENT,FAMILY MEDICAL HISTORY|RECENT,ASSESSMENT|TODAY
  concept: REASON FOR SPECIAL CARE|Weight less than 2500g,UNDER 5 VISIT|Weight,SURGICAL HISTORY|Ever had any surgical procedure?,SUPPLEMENTATION|Visit date,MEDICAL HISTORY|Child ever had asthma?,IMMUNIZATION RECORD|Mother HIV Status,FAMILY MEDICAL HISTORY|Has family a history of allergies?,ASSESSMENT|Cyanosis
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

development:
  label.encounter.map: UNDER 5 VISIT|UNDER 5 VISIT,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,IMMUNIZATION RECORD|IMMUNIZATION RECORD,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,MEDICAL HISTORY|MEDICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,SURGICAL HISTORY|SURGICAL HISTORY,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: REASON FOR SPECIAL CARE|RECENT,UNDER 5 VISIT|TODAY,SURGICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,SUPPLEMENTATION|TODAY,MEDICAL HISTORY|RECENT,IMMUNIZATION RECORD|RECENT,FAMILY MEDICAL HISTORY|RECENT,ASSESSMENT|TODAY
  concept: REASON FOR SPECIAL CARE|Weight less than 2500g,UNDER 5 VISIT|Weight,SURGICAL HISTORY|Ever had any surgical procedure?,SUPPLEMENTATION|Visit date,MEDICAL HISTORY|Child ever had asthma?,IMMUNIZATION RECORD|Mother HIV Status,FAMILY MEDICAL HISTORY|Has family a history of allergies?,ASSESSMENT|Cyanosis
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

test: &TEST
  label.encounter.map: UNDER 5 VISIT|UNDER 5 VISIT,SUPPLEMENTATION|VITAMIN A SUPPLEMENTATION AND DE-WORMING SCHEDULE,IMMUNIZATION RECORD|IMMUNIZATION RECORD,ASSESSMENT|ASSESSMENT AT ONE WEEK POSTNATAL CHECK,MEDICAL HISTORY|MEDICAL HISTORY,INITIAL NEW BORN RECORD|INITIAL NEW-BORN RECORD,SURGICAL HISTORY|SURGICAL HISTORY,REASON FOR SPECIAL CARE|REASON FOR SPECIAL CARE,FAMILY MEDICAL HISTORY|FAMILY MEDICAL HISTORY
  clinical.encounters.sequential.list: ASSESSMENT,FAMILY MEDICAL HISTORY,IMMUNIZATION RECORD,INITIAL NEW BORN RECORD,MEDICAL HISTORY,REASON FOR SPECIAL CARE,SUPPLEMENTATION,SURGICAL HISTORY,UNDER 5 VISIT
  clinical.encounters.display.list: ASSESSMENT;FAMILY MEDICAL HISTORY;IMMUNIZATION RECORD;INITIAL NEW BORN RECORD;MEDICAL HISTORY;REASON FOR SPECIAL CARE;SUPPLEMENTATION;SURGICAL HISTORY;UNDER 5 VISIT
  scope: REASON FOR SPECIAL CARE|RECENT,UNDER 5 VISIT|TODAY,SURGICAL HISTORY|RECENT,INITIAL NEW BORN RECORD|EXISTS,SUPPLEMENTATION|TODAY,MEDICAL HISTORY|RECENT,IMMUNIZATION RECORD|RECENT,FAMILY MEDICAL HISTORY|RECENT,ASSESSMENT|TODAY
  concept: REASON FOR SPECIAL CARE|Weight less than 2500g,UNDER 5 VISIT|Weight,SURGICAL HISTORY|Ever had any surgical procedure?,SUPPLEMENTATION|Visit date,MEDICAL HISTORY|Child ever had asthma?,IMMUNIZATION RECORD|Mother HIV Status,FAMILY MEDICAL HISTORY|Has family a history of allergies?,ASSESSMENT|Cyanosis
  label: SUPPLEMENTATION|Supplementation,ASSESSMENT|Assessment

assessment: u5_protocol_patients

family_medical_history: u5_protocol_patients

immunization_record: u5_protocol_patients

initial_new_born_record: u5_protocol_patients

medical_history: u5_protocol_patients

reason_for_special_care: u5_protocol_patients

supplementation: u5_protocol_patients

surgical_history: u5_protocol_patients

under_5_visit: u5_protocol_patients
